version: "3.7"

services:
  frontend:
    image: petercha2000/42club:0.0.1
    build:
      context: .
      dockerfile: Dockerfile.prod
    env_file:
      - /home/ubuntu/Production/42Club/.env
    platform: linux/amd64
    restart: always
    networks:
      web_gate:
        aliases:
          - 42club

networks:
  web_gate:
    driver: bridge
    external: true

