version: "3.7"

services:
  frontend:
    image: petercha2000/42club:0.0.1
    build:
      context: .
      dockerfile: Dockerfile.prod
    platform: linux/amd64
    restart: always
    networks:
      gate_net:
        aliases:
          - 42club

networks:
  gate_net:
    driver: bridge
    external: true

