version: "3.7"

services:
  frontend:
    image: petercha2000/42club:0.0.1
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        PUBLIC_URL: $PUBLIC_URL
        REACT_APP_SPREADSHEET_ID: $REACT_APP_SPREADSHEET_ID
        REACT_APP_SHEET_ID: $REACT_APP_SHEET_ID
        REACT_APP_GOOGLE_CLIENT_EMAIL: $REACT_APP_GOOGLE_CLIENT_EMAIL
        REACT_APP_GOOGLE_SERVICE_PRIVATE_KEY: $REACT_APP_GOOGLE_SERVICE_PRIVATE_KEY
    platform: linux/amd64
    restart: always
    networks:
      - web_gate

networks:
  web_gate:
    driver: bridge
    external: true

