FROM node:13.12.0-alpine as build

WORKDIR /app

ENV PUBLIC_URL=https://heyinsa.kr/42club
ENV PATH /app/node_modules/.bin:$PATH

COPY package*.json ./

RUN npm ci --silent \
    && npm install react-scripts@3.4.1 -g --silent

COPY . ./

RUN npm run build

# production environment

FROM nginx:stable-alpine

COPY --from=build /app/build  /var/www/html/static/

COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
