name: Build And Push Docker Image

on:
  push: 
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile.prod
        push: true
        tags: petercha2000/42club:0.0.1
        build-args: |
          REACT_APP_SPREADSHEET_ID=${{ secrets.REACT_APP_SPREADSHEET_ID }}
          REACT_APP_SHEET_ID=${{ secrets.REACT_APP_SHEET_ID }}
          REACT_APP_GOOGLE_CLIENT_EMAIL=${{ secrets.REACT_APP_GOOGLE_CLIENT_EMAIL }}
          REACT_APP_GOOGLE_SERVICE_PRIVATE_KEY=${{ secrets.REACT_APP_GOOGLE_SERVICE_PRIVATE_KEY }}
          PUBLIC_URL=${{ secrets.PUBLIC_URL }}
          HI="hihihi"

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using key
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          ./deploy-42club.sh
